error: Add backtraces to ChildFailure and ChildKilled
The plan is to have more hierarchical error types so it's easier
to find exactly where in the deployment flow an error occurred.